### ISSUE TITLE
找不到item 直接就Not Found

### ISSUE THREAD

**Issue by linwenjun** [YingjiaZhang/101-jersey-web#1]
见
[https://github.com/YingjiaZhang/101-jersey-web/blob/master/src/main/java/school/thoughtworks/pos/resource/RootResource.java#L62](https://github.com/YingjiaZhang/101-jersey-web/blob/master/src/main/java/school/thoughtworks/pos/resource/RootResource.java#L62)

**Comment by YingjiaZhang** [comment]
commit 30a9a2172d7c2c3553baad23a8659a28b206b2e3
Author: YingjiaZhang <zhyingjia@163.com>
Date:   Thu Jan 19 10:24:55 2017 +0800

    fixed if not found then return 404
