### ISSUE TITLE
category为什么要写死1

### ISSUE THREAD

**Issue by linwenjun** [YingjiaZhang/101-jersey-web#3]
https://github.com/YingjiaZhang/101-jersey-web/blob/master/src/main/java/school/thoughtworks/pos/resource/RootResource.java#L78

**Comment by YingjiaZhang** [comment]
原因 ： 默认类型为1，为all；
理解： 如果没有给类型就给一个默认类型，比如1；如果有类型就用传递过来的类型？
已更改。
commit 9d9f9006317c0861604909bb405ee398c57363a4
Author: YingjiaZhang <zhyingjia@163.com>
Date:   Thu Jan 19 10:33:36 2017 +0800

    fixed value about  categoryId
