### ISSUE TITLE
如果删掉一个类别，而其中有商品，会怎么样

### ISSUE THREAD

**Issue by linwenjun** [YingjiaZhang/101-jersey-web#4]
https://github.com/YingjiaZhang/101-jersey-web/blob/master/src/main/java/school/thoughtworks/pos/resource/CategoryResource.java#L48

**Comment by YingjiaZhang** [comment]
当前 ： state code  为 500
理解：是不是应该加个 `try {..} catch {..}` 出现异常的情况我们认为是有外键约束拒绝删除？ 然后给个412 / 403
HTTP Status 412 （未满足前提条件）
HTTP Status 403 （禁止）-> 服务器拒绝请求。

**Comment by YingjiaZhang** [comment]
还是说，删除一个类别的时候，如果其中还有商品，那么就给那些商品的类别置1（表示在分类1,类型为all，表示未分类的商品）?

**Comment by YingjiaZhang** [comment]
这个还没改，前三个都改了，没网还没提交上去，老师你先看一下我的理解有什么问题没有？

**Comment by linwenjun** [comment]
不能简单加 try catch 
可以做逻辑判断，HTTP Status 412 （未满足前提条件）比较合适，另外需要返回 message 字段

**Comment by YingjiaZhang** [comment]
commit 56a6f5737c579788b5657a15f66e1d389d027ae1
Author: YingjiaZhang <zhyingjia@163.com>
Date:   Sat Jan 21 11:59:00 2017 +0800

    update api.raml about delete /categories/id

commit 6114838e3e14b30a38aa5806a8aca0f044f6126e
Author: YingjiaZhang <zhyingjia@163.com>
Date:   Sat Jan 21 11:49:35 2017 +0800

    fixed delete /categories/id
